%%{init: {
  'theme': 'forest',
  'themeVariables': {
    'background': '#ffffff',
    'mainBkg': '#f9f9f9',
    'secondBkg': '#efefef'
  }
}}%%
sequenceDiagram
    autonumber

    title 1.1. Message Processing Flow (insert new)
    
    participant Client 
    participant API as ApiServer
    participant Receiver
    participant Queue
    
    Note over Client: Message Submission
    Client->>API: POST /api/messages

    Note over API: Authorization: Bearer token
    API->>API: Validate token

    rect rgb(255, 200, 200)
        alt Tokern Invalid
            API->>Client: 401 Unauthorized
        else Token Valid
            API->>API: Validate message schema
        end
    end
    
    
    
    
    rect rgb(255, 200, 200)
        alt Message Invalid
            API->>Client: 400 Bad Request
        else Message Valid
            Note over API: Message Processing
            API->>Receiver: Process message
            Receiver->>Receiver: Validate message (length, priority)
        end
    end

    rect rgb(255, 200, 200)
        alt Message Invalid
            Receiver-->>API: Validation failed
            API-->>Client: 400 Bad Request
        else Message Valid
            Receiver->>Queue: Store message by priority
            Queue->>Queue: Add to priority queue
            Receiver-->>API: Message accepted
            API-->>Client: 200 Success + messageId
        end
    end